// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuy1VKUb0n53qjWoLxf9CXJ5h4qGX8NRM',
    appId: '1:223572198619:ios:0c77f8967b8b84516db8fe',
    messagingSenderId: '223572198619',
    projectId: 'flutter-induk-202316003',
    storageBucket: 'flutter-induk-202316003.firebasestorage.app',
    iosBundleId: 'com.example.gittest',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJeCfcWPn6_0AHXFz2lFT1f19l4MYS9oE',
    appId: '1:223572198619:android:e55384838935c1896db8fe',
    messagingSenderId: '223572198619',
    projectId: 'flutter-induk-202316003',
    storageBucket: 'flutter-induk-202316003.firebasestorage.app',
  );

}